More smoother camera X movement
maskbearer/prototype pull request #1
Opened 2021-11-04 14:03 UTC by JavaJump3r

2021-11-05 19:16 UTC, Maligan requested changes
Also you have excess changes like:
user.keystore
ProjectSettings.asset
Bench.prefab

2021-11-05 19:16 UTC, Maligan commented on Assets/Game/Scripts/Actor/Objects/Player/Player.cs
> -    private Vector2 velocity;
It's better to add extra property than expose field to public

`public Vector2 Velocity => velocity`

2021-11-05 19:16 UTC, Maligan commented on Assets/Game/Scripts/Actor/Objects/Player/PlayerCameraController.cs
> +    async void FadeIn(float time)
These methods - FadeIn / FadeOut are

1) unsused
2) async

What did you want to do by them?

2021-11-05 19:16 UTC, Maligan commented on Assets/Game/Scripts/Actor/Objects/Player/CameraAnchor.cs
> +public class CameraAnchor : MonoBehaviour
Could you consider to merge this class with PlayerCameraController?

As I understood this's used for horizontal following/offset, we have code for vertical in PlayerCameraController. It's better to keep all following/anchor/movement code in one place. Right now I can't understand why they should be separated - explain why if you insist on that.

2021-11-05 19:16 UTC, Maligan commented on Assets/Game/Scripts/Actor/Objects/Player/CameraAnchor.cs
> +        var wtf = (this.transform.localPosition.x * smoothness + player.velocity.x / 6 * XOffset) / (smoothness + 1);
wtf?

2021-11-07 14:12 UTC, Maligan requested changes
Much better, It's really good idea to balance offset while running!
Need some small changes and I'll accept it!

2021-11-07 14:12 UTC, Maligan commented on Assets/Game/Scripts/Utils/MbLib.cs
> +public static class MbLib
Really good idea to make it in standalone class but I got the problem which was with Mathf.Sign:

According to the docs 0 return +1
https://docs.unity3d.com/ScriptReference/Mathf.Sign.html

It's better to use System.Math.Sign witch works like this method and not to create one more class.

2021-11-07 14:12 UTC, Maligan commented on Assets/Game/Scripts/Actor/Objects/Player/PlayerCameraController.cs
> +        _flip = GameObject.Find("Flip");
If you want to get some child / descendant it's better to use `transfrom.Find` because GameObject.Find() iterate over ALL objects in all scenes and you can find incorrect "Flip" GameObject

2021-11-07 14:12 UTC, Maligan commented on Assets/Game/Scripts/Actor/Objects/Player/PlayerCameraController.cs
> +        var anchorXPos = Mathf.Sign(_flip.transform.localScale.x) * XOffset + _player.Velocity.x * XOffsetRun/settings.moveVelocity;
After merging Anchor with PlayerCameraController you don't really need subobject "Anchor"
Look at how you use it here - you need only something like `_offsetY` value, you can get rid of this complexity, I suggest something like this:

```
    private void UpdateFollow()
    {
        if (_player == null)
            return;

        _offsetX = Math.Sign(_flip.transform.localScale.x) * XOffset
                 + Math.Sign(_player.Velocity.x) * XOffsetRun;

        var targetPos = _player.transform.position;
        targetPos.x += _offsetX;
        targetPos.y += _offsetY + 1.5f;

        // Lerp
        _cameraPosition.x = Mathf.Lerp(_cameraPosition.x, targetPos.x, _cameraDefaultHLerpSpeed * Time.deltaTime);
        _cameraPosition.y = Mathf.Lerp(_cameraPosition.y, targetPos.y, _cameraDefaultVLerpSpeed * Time.deltaTime);
    }
```

In this snippet also used `_cameraDefaultHLerpSpeed` and Lerping by x/y are in one place and equal that is easy to understand

2021-11-07 14:22 UTC, JavaJump3r commented on Assets/Game/Scripts/Actor/Objects/Player/PlayerCameraController.cs
> +        var anchorXPos = Mathf.Sign(_flip.transform.localScale.x) * XOffset + _player.Velocity.x * XOffsetRun/settings.moveVelocity;
k

2021-11-07 14:42 UTC, JavaJump3r commented on Assets/Game/Scripts/Actor/Objects/Player/PlayerCameraController.cs
> +        var anchorXPos = Mathf.Sign(_flip.transform.localScale.x) * XOffset + _player.Velocity.x * XOffsetRun/settings.moveVelocity;
Sorry for russian for everyone esle
Я думаю якорь будет полезным для закрепления камеры в специфичных местах по типу камер боссов, или просто для её простого перемещения

2021-11-23 10:13 UTC, closed without merging